// frontend/pages/auth.vue
<template>
  <div class="min-h-screen bg-gray-50 flex items-center justify-center p-6">
    <div class="w-full max-w-2xl bg-white rounded-2xl shadow-sm border border-gray-200 p-8">
      <h1 class="text-2xl font-bold text-gray-900 mb-6 text-center">Create an account or Sign in</h1>

      <!-- Role selector -->
      <div class="flex justify-center gap-3 mb-8">
        <button
          class="px-4 py-2 rounded-lg border"
          :class="role === 'client' ? 'bg-primary-600 text-white border-primary-600' : 'bg-white text-gray-700 border-gray-300'"
          @click="role = 'client'"
        >Student</button>
        <button
          class="px-4 py-2 rounded-lg border"
          :class="role === 'expert' ? 'bg-primary-600 text-white border-primary-600' : 'bg-white text-gray-700 border-gray-300'"
          @click="role = 'expert'"
        >Expert</button>
        <button
          class="px-4 py-2 rounded-lg border"
          :class="role === 'admin' ? 'bg-primary-600 text-white border-primary-600' : 'bg-white text-gray-700 border-gray-300'"
          @click="role = 'admin'"
        >Admin</button>
      </div>

      <!-- Tabs -->
      <div class="flex justify-center gap-4 mb-6">
        <button
          class="px-3 py-1 rounded-md"
          :class="mode === 'signup' ? 'bg-primary-600 text-white' : 'bg-gray-100 text-gray-700'"
          @click="mode = 'signup'"
        >Sign up</button>
        <button
          class="px-3 py-1 rounded-md"
          :class="mode === 'signin' ? 'bg-primary-600 text-white' : 'bg-gray-100 text-gray-700'"
          @click="mode = 'signin'"
        >Sign in</button>
      </div>

      <!-- Forms -->
      <form @submit.prevent="handleSubmit" class="space-y-4 max-w-xl mx-auto">
        <div v-if="mode === 'signup'" class="grid grid-cols-2 gap-4">
          <div>
            <label class="block text-sm text-gray-600 mb-1">First name</label>
            <input v-model="firstName" type="text" class="input-primary w-full" required />
          </div>
          <div>
            <label class="block text-sm text-gray-600 mb-1">Last name</label>
            <input v-model="lastName" type="text" class="input-primary w-full" required />
          </div>
        </div>

        <div>
          <label class="block text-sm text-gray-600 mb-1">Email</label>
          <input v-model="email" type="email" class="input-primary w-full" required />
        </div>

        <div>
          <label class="block text-sm text-gray-600 mb-1">Password</label>
          <input v-model="password" type="password" class="input-primary w-full" required />
        </div>

        <button type="submit" class="btn-primary w-full mt-2">
          {{ mode === 'signup' ? actionLabel : 'Sign in' }}
        </button>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '~/stores/auth'

const router = useRouter()
const auth = useAuthStore()

const role = ref<'client' | 'expert' | 'admin'>('client')
const mode = ref<'signup' | 'signin'>('signup')

const firstName = ref('')
const lastName = ref('')
const email = ref('')
const password = ref('')

const actionLabel = computed(() => {
  if (role.value === 'client') return 'Create student account'
  if (role.value === 'expert') return 'Apply as expert'
  return 'Admin account (manual only)'
})

const handleSubmit = async () => {
  try {
    if (mode.value === 'signup') {
      if (role.value === 'admin') {
        // Admin signup is manual-only; allow direct sign-in if credentials exist
        await auth.login(email.value, password.value)
      } else {
        const name = `${firstName.value} ${lastName.value}`.trim()
        // @ts-ignore: Role string accepted by store
        await auth.register(email.value, password.value, name, role.value)
      }
    } else {
      await auth.login(email.value, password.value)
    }

    // Role-based redirect
    const userRole = auth.userRole
    if (userRole === 'admin') {
      router.push('/admin/dashboard')
    } else if (userRole === 'expert') {
      router.push('/reviews')
    } else {
      router.push('/dashboard')
    }
  } catch (e) {
    console.error(e)
    alert('Authentication failed. Please check your details and try again.')
  }
}
</script>

<style scoped>
/* Tailwind utility classes are used; no custom styles */
</style>

// frontend/app/auth/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { useAuthStore } from '@/stores/authStore'
import { UserRole } from '@/types'
import { LogIn, UserPlus, Mail, Lock, User } from 'lucide-react'
import toast from 'react-hot-toast'

export default function AuthPage() {
  const router = useRouter()
  const { login, isLoading } = useAuthStore()
  const [isLogin, setIsLogin] = useState(true)
  const [role, setRole] = useState<'client' | 'expert' | 'admin'>('client')
  
  const [loginForm, setLoginForm] = useState({
    email: '',
    password: ''
  })
  
  const [signupForm, setSignupForm] = useState({
    email: '',
    password: '',
    firstName: '',
    lastName: '',
    role: UserRole.CLIENT
  })

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault()
    
    try {
      const response = await login(loginForm.email, loginForm.password)
      
      if (response.success) {
        toast.success('Login successful!')
        
        // Redirect based on role
        const userRole = response.user?.role
        if (userRole === UserRole.ADMIN) {
          router.push('/admin/dashboard')
        } else if (userRole === UserRole.EXPERT) {
          router.push('/expert/reviews')
        } else {
          router.push('/dashboard')
        }
      } else {
        toast.error(response.message || 'Login failed')
      }
    } catch (error: any) {
      toast.error(error.message || 'Login failed')
    }
  }

  const handleSignup = async (e: React.FormEvent) => {
    e.preventDefault()
    toast.info('Registration feature coming soon')
  }

  const loginWithDemo = async (roleType: 'client' | 'expert' | 'admin') => {
    const demos = {
      client: { email: 'client@demo.com', password: 'demo123' },
      expert: { email: 'expert@demo.com', password: 'demo123' },
      admin: { email: 'admin@demo.com', password: 'demo123' }
    }
    
    setLoginForm(demos[roleType])
    const response = await login(demos[roleType].email, demos[roleType].password)
    
    if (response.success) {
      toast.success(`Logged in as ${roleType}`)
      const userRole = response.user?.role
      if (userRole === UserRole.ADMIN) {
        router.push('/admin/dashboard')
      } else if (userRole === UserRole.EXPERT) {
        router.push('/expert/reviews')
      } else {
        router.push('/dashboard')
      }
    }
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50 flex items-center justify-center p-4">
      <div className="w-full max-w-md">
        <div className="bg-white rounded-2xl shadow-xl p-8">
          {/* Logo */}
          <div className="text-center mb-8">
            <div className="w-16 h-16 bg-gradient-to-br from-blue-500 to-purple-600 rounded-2xl flex items-center justify-center mx-auto mb-4">
              <User className="w-8 h-8 text-white" />
            </div>
            <h1 className="text-2xl font-bold text-gray-900">AL-Tech Academy</h1>
            <p className="text-sm text-gray-500 mt-1">AI-Powered Q&A System</p>
          </div>

          {/* Role Selection */}
          <div className="flex gap-2 mb-6 p-1 bg-gray-100 rounded-lg">
            {(['client', 'expert', 'admin'] as const).map((r) => (
              <button
                key={r}
                onClick={() => setRole(r)}
                className={`flex-1 py-2 px-3 rounded-md text-sm font-medium transition-colors ${
                  role === r
                    ? 'bg-white text-gray-900 shadow-sm'
                    : 'text-gray-600 hover:text-gray-900'
                }`}
              >
                {r.charAt(0).toUpperCase() + r.slice(1)}
              </button>
            ))}
          </div>

          {/* Toggle Login/Signup */}
          <div className="flex gap-2 mb-6">
            <button
              onClick={() => setIsLogin(true)}
              className={`flex-1 py-2 px-4 rounded-lg font-medium transition-colors ${
                isLogin
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              <LogIn className="w-4 h-4 inline mr-2" />
              Sign In
            </button>
            <button
              onClick={() => setIsLogin(false)}
              className={`flex-1 py-2 px-4 rounded-lg font-medium transition-colors ${
                !isLogin
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              <UserPlus className="w-4 h-4 inline mr-2" />
              Sign Up
            </button>
          </div>

          {/* Login Form */}
          {isLogin ? (
            <form onSubmit={handleLogin} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Email
                </label>
                <div className="relative">
                  <Mail className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                  <input
                    type="email"
                    value={loginForm.email}
                    onChange={(e) => setLoginForm({ ...loginForm, email: e.target.value })}
                    required
                    className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    placeholder="Enter your email"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Password
                </label>
                <div className="relative">
                  <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                  <input
                    type="password"
                    value={loginForm.password}
                    onChange={(e) => setLoginForm({ ...loginForm, password: e.target.value })}
                    required
                    className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    placeholder="Enter your password"
                  />
                </div>
              </div>

              <button
                type="submit"
                disabled={isLoading}
                className="w-full btn-primary"
              >
                {isLoading ? 'Signing In...' : 'Sign In'}
              </button>
            </form>
          ) : (
            <form onSubmit={handleSignup} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    First Name
                  </label>
                  <input
                    type="text"
                    value={signupForm.firstName}
                    onChange={(e) => setSignupForm({ ...signupForm, firstName: e.target.value })}
                    required
                    className="w-full input-primary"
                    placeholder="First name"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Last Name
                  </label>
                  <input
                    type="text"
                    value={signupForm.lastName}
                    onChange={(e) => setSignupForm({ ...signupForm, lastName: e.target.value })}
                    required
                    className="w-full input-primary"
                    placeholder="Last name"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Email
                </label>
                <input
                  type="email"
                  value={signupForm.email}
                  onChange={(e) => setSignupForm({ ...signupForm, email: e.target.value })}
                  required
                  className="w-full input-primary"
                  placeholder="Enter your email"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Password
                </label>
                <input
                  type="password"
                  value={signupForm.password}
                  onChange={(e) => setSignupForm({ ...signupForm, password: e.target.value })}
                  required
                  minLength={8}
                  className="w-full input-primary"
                  placeholder="At least 8 characters"
                />
              </div>

              <button
                type="submit"
                className="w-full btn-primary"
              >
                Create Account
              </button>
            </form>
          )}

          {/* Demo Login Buttons */}
          <div className="mt-6 pt-6 border-t border-gray-200">
            <p className="text-xs text-gray-500 text-center mb-3">Or login with demo account:</p>
            <div className="grid grid-cols-3 gap-2">
              <button
                onClick={() => loginWithDemo('client')}
                className="py-2 px-3 text-xs bg-blue-50 text-blue-600 rounded-lg hover:bg-blue-100 transition-colors"
              >
                Client
              </button>
              <button
                onClick={() => loginWithDemo('expert')}
                className="py-2 px-3 text-xs bg-green-50 text-green-600 rounded-lg hover:bg-green-100 transition-colors"
              >
                Expert
              </button>
              <button
                onClick={() => loginWithDemo('admin')}
                className="py-2 px-3 text-xs bg-purple-50 text-purple-600 rounded-lg hover:bg-purple-100 transition-colors"
              >
                Admin
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
